# routes/history_routes.py
from fastapi import APIRouter, Depends, Query, HTTPException
from typing import List, Optional
from pydantic import BaseModel
from services.history_service import (
    get_trades,
    get_trade_by_id,
    append_trade,
)

router = APIRouter(tags=["History"])


class TradeOut(BaseModel):
    id: str
    symbol: Optional[str]
    side: Optional[str]
    qty: Optional[float]
    price: Optional[float]
    status: Optional[str]
    profit: Optional[float]
    created_at: Optional[str]


class PaginatedTrades(BaseModel):
    total: int
    limit: int
    offset: int
    trades: List[TradeOut]


@router.get("/", response_model=PaginatedTrades)
def list_trades(
    limit: int = Query(50, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    symbol: Optional[str] = Query(None, description="Filter by trading pair, e.g. BTCUSDT"),
    status: Optional[str] = Query(None, description="Filter by trade status"),
):
    """
    List trade history (paginated). Protected by JWT auth.
    """
    trades, total = get_trades(limit=limit, offset=offset, symbol=symbol, status=status)
    return {"total": total, "limit": limit, "offset": offset, "trades": trades}


@router.get("/{trade_id}", response_model=TradeOut)
def get_trade(trade_id: str):
    """
    Return a single trade by id. Protected by JWT auth.
    """
    t = get_trade_by_id(trade_id)
    if not t:
        raise HTTPException(status_code=404, detail="Trade not found")
    return t


@router.post("/", response_model=TradeOut)
def create_trade(payload: dict):
    """
    Add a trade record (useful for testing or internal services).
    Protected by JWT auth.
    The payload should contain at least 'id' or will be auto-generated by the service.
    """
    t = append_trade(payload)
    return t
